### ISSUE TITLE
Would a 6 wheel rover with rocker-bogie suspension be drivable with your ackermann drive model?

### ISSUE THREAD

**Issue by Mechazo11** [berickson/sim_car#11]
Hi @berickson 

Thank you very much for open-sourcing this project. I was wondering if we used a small 6 wheel rover that uses rocker-bogie suspension, can your ackermann drive model work on that vehicle?

With best
@Mechazo11

**Comment by berickson** [comment]
Sorry, but no. This is a 4 wheeled car simulation.
