### ISSUE TITLE
Errors in RVIZ when running bringup.launch.py

### ISSUE THREAD

**Issue by berickson** [berickson/sim_car#2]
Intermittently, errors appear in RVIZ after running bringup.launch.py: 

From https://github.com/berickson/sim_car/pull/1#issuecomment-1281899687

```text
[rviz2-3] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 93 in ./src/buffer_core.cpp
[component_container_isolated-8] [INFO] [1666075407.181868278] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
```
Gazebo starts and robot and lidar is visible. Errors in rviz:
1. `Global status: ERROR` -> `Fixed frame` -> `Frame [map] does not exist`
2. `Robot model` -> `Status: ERROR` -> `Not transform from [...] to [map]`
3. `Map` -> `Status: WARNING` -> `No map received`

This issue appears in Humble, but Galactic is reported to work fine.

**Comment by robodrome** [comment]
Perhaps this migration guide from `Galactic` to `Humble` helps?
https://navigation.ros.org/migration/Galactic.html#spawning-the-robot-in-gazebo

**Comment by berickson** [comment]
Joint position timestamps were zero. This was keeping robot state publisher from translating joint positions into TF frames.
