### ISSUE TITLE
can not move the robot in circle

### ISSUE THREAD

**Issue by MohiniMohiniMohini** [berickson/sim_car#3]
there is a drift in the robot. I am not able to move it in a circle. tried it with twist msg and with Ackermann msg both. the closest I could get is it completes a circle with a drift.

**Comment by berickson** [comment]
I tried to reproduce, and I'm getting nearly perfect circles.  It drifts a bit if you wait long enough, but no more than a real car would.  Are you seeing something more severe?

Here is what I did:

`ros2 topic pub /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 0.5, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 1.0}}"`

Can you post more info? Maybe a video?

**Comment by MohiniMohiniMohini** [comment]
Hello @berickson , thanks for the reply. Yes, this is what I mean. the car starts the drift right with 1st circle. What I expect is the car to make at least one perfect circle. is this the best circle it can make?


Also the equivalent command for Ackermann will be:
ros2 topic pub -r 50 /car/cmd_ackermann ackermann_msgs/msg/AckermannDriveStamped "{drive: {steering_angle: 1.0, steering_angle_velocity: 0.0, speed: 0.5, acceleration: 0.0, jerk: 0.0}}"

**Comment by berickson** [comment]
I don't think I'm seeing the same thing you are seeing.  Here it is driving with your command: [https://youtu.be/uFVwAu7Ol0s](url)

**Comment by MohiniMohiniMohini** [comment]
Looks like there is no problem in this video, i have written a marker node and on rviz i can see the difference. here is a plot of 1 circle. the drift is observed from 1st time the robot comes back
![image](https://user-images.githubusercontent.com/22427829/204255350-26c968b7-6276-449a-bdeb-94806daa0156.png)

**Comment by berickson** [comment]
My goal is to model real vehicles, in the case it's a Traxxas Slash.  The real car will have imperfect suspension, wheel slippage, motor vibration, the floor will have uneven friction, etc.  You won't be able to get a circle even as good as in your graph with any real car. 

I think that drift is well within what I would expect from the simulation.

**Comment by MohiniMohiniMohini** [comment]
okay, @berickson . thanks for the reply.
