### ISSUE TITLE
Getting Started launch bringup.launch.py returns error

### ISSUE THREAD

**Issue by Steven7099** [berickson/sim_car#5]
I used this a few times in the past few weeks and it worked fine. I re-cloned the repository today and when I run `ros2 launch sim_car bringup.launch.py` it returns the error below. 

I did update my Ubuntu yesterday as it popped up on my monitor screen. I did notice there were a lot of updates for ROS so maybe this could be the issue.

```
[component_container_isolated-7]          at line 235 in ./src/buffer_core.cpp
[component_container_isolated-7] Error:   TF_NAN_INPUT: Ignoring transform for child_frame_id "back_left_wheel_shock" from authority "Authority undetectable" because of a nan value in the transform (-nan -nan -nan) (0.000000 0.000000 0.000000 1.000000)
```
![screenshot](https://user-images.githubusercontent.com/90917646/209142534-12d5b1f5-ef22-453c-a673-56caf70f6561.png)
![Screenshot from 2022-12-22 09-35-25](https://user-images.githubusercontent.com/90917646/209145897-ef9616fb-8813-461a-b603-b6c04726a952.png)

**Comment by Steven7099** [comment]
I did a fresh install of Ubuntu 22 and Humble on another computer and also got the same error.

**Comment by Steven7099** [comment]
Tried it again today and it worked. Not sure what happened on my end because I tried creating a new ws a few times.

**Comment by berickson** [comment]
Glad you got it working.
